--Database Basics MS SQL Exam – 13 October 2019
--CREATE DATABASE Bitbucket
GO
--USE Bitbucket
GO

CREATE TABLE Users
(
Id INT IDENTITY PRIMARY KEY,
Username NVARCHAR(30) NOT NULL,
[Password] NVARCHAR(30) NOT NULL,
Email NVARCHAR(50) NOT NULL,
)

CREATE TABLE Repositories
(
Id INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(50) NOT NULL,
)

CREATE TABLE RepositoriesContributors
(
RepositoryId INT FOREIGN KEY REFERENCES Repositories(Id) NOT NULL,
ContributorId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
CONSTRAINT PK_RepositoriesContributor PRIMARY KEY (RepositoryId, ContributorId),
)

CREATE TABLE Issues
(
Id INT IDENTITY PRIMARY KEY,
Title NVARCHAR(255) NOT NULL,
IssueStatus NCHAR(6) NOT NULL,
RepositoryId INT FOREIGN KEY REFERENCES Repositories(Id) NOT NULL,
AssigneeId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
)

CREATE TABLE Commits
(
Id INT IDENTITY PRIMARY KEY,
[Message] NVARCHAR(255) NOT NULL,
IssueId INT FOREIGN KEY REFERENCES Issues(Id),
RepositoryId INT FOREIGN KEY REFERENCES Repositories(Id) NOT NULL,
ContributorId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
)

CREATE TABLE Files
(
Id INT IDENTITY PRIMARY KEY,
[Name] NVARCHAR(100) NOT NULL,
Size DECIMAL (18,2) NOT NULL,
ParentId INT FOREIGN KEY REFERENCES Files(Id),
CommitId INT FOREIGN KEY REFERENCES Commits(Id) NOT NULL,
)